<a href="https://colab.research.google.com/github/thangvle/smart_pros/blob/master/4D%20Tensorflow%20example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:

## here is an example for simple CNN of 4D operation with Tensorflow
import tensorflow as tf

#Building graph

input = tf.Variable(tf.random_normal([1, 10, 10, 1]))
filter = tf.Variable(tf.random_normal([3, 3, 1, 1]))
op = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='VALID')
op2 = tf.nn.conv2d(input, filter, strides=[1, 1, 1, 1], padding='SAME')

#Initialization and session
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)

    print("Input \n")
    print('{0} \n'.format(input.eval()))
    print("Filter/Kernel \n")
    print('{0} \n'.format(filter.eval()))
    print("Result/Feature Map with valid positions \n")
    result = sess.run(op)
    print(result)
    print('\n')
    print("Result/Feature Map with padding \n")
    result2 = sess.run(op2)
    print(result2)



Input 

[[[[ 1.2089142e+00]
   [ 1.7547523e+00]
   [ 1.4075144e-01]
   [ 1.1301579e+00]
   [-1.7872370e+00]
   [ 2.1926813e+00]
   [ 8.7944973e-01]
   [-2.0044901e+00]
   [-9.8094743e-01]
   [ 7.0307177e-01]]

  [[-3.6329627e-01]
   [ 9.3051964e-01]
   [ 6.8089239e-02]
   [-1.9195771e+00]
   [-4.8608124e-01]
   [-2.6312166e-01]
   [ 9.9239808e-01]
   [-5.6472147e-01]
   [ 9.5029831e-01]
   [-5.4583497e-02]]

  [[-1.3816344e+00]
   [ 1.1056679e+00]
   [ 1.6369715e+00]
   [ 1.5073898e+00]
   [ 5.2514851e-01]
   [-1.2695768e+00]
   [ 2.9011469e+00]
   [-6.9290853e-01]
   [-3.8336301e-01]
   [-1.4199759e-02]]

  [[-1.1382568e+00]
   [ 6.1977839e-01]
   [-9.6905164e-02]
   [-2.3691063e-01]
   [ 1.8069658e+00]
   [-8.9462250e-03]
   [ 4.8346880e-01]
   [ 1.7169957e+00]
   [-1.2381121e+00]
   [ 1.0379556e+00]]

  [[ 1.4471792e+00]
   [-2.8046107e-01]
   [-2.3718090e-01]
   [ 2.3107538e-03]
   [ 4.9588791e-01]
   [-7.0983954e-02]
   [ 1.9456814e-01]
   [ 2.2718041e+00]
   [-9.4073698e-02]
   [